# Generated by Django 3.2.20 on 2023-09-13 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopper',
            name='username',
        ),
        migrations.AlterField(
            model_name='shopper',
            name='email',
            field=models.EmailField(max_length=255, unique=True),
        ),
    ]
