# Generated by Django 3.2.20 on 2023-09-12 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='strip_id',
            field=models.CharField(blank=True, max_length=90),
        ),
    ]
